"""Frozen-application entry point.

A console script is generated by pip from the `[project.scripts]` table and
does not exist in a frozen bundle, so PyInstaller needs a real module to
start from. Kept here rather than in the package because it is a property
of how darlaston is shipped, not of what it does.
"""
import multiprocessing
import sys


def selftest() -> int:
    """Can this build reach everything it needs?

    Only meaningful in a bundle, which is why it lives here rather than in
    the package: from a source checkout the fonts and icons are on disk
    whether or not anything packaged them, so the same check run against
    the source tree passes unconditionally and proves nothing. The wheel
    shipped without its fonts and icons once for exactly that reason, and
    nobody noticed, because everybody testing it had a clone.

    Also worth having in a stranger's hands: "run darlaston --selftest and
    paste what it says" is a better first support question than any number
    of screenshots.
    """
    import os

    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

    import cv2
    import numpy
    from PySide6 import QtCore, QtWidgets

    from darlaston import __version__
    from darlaston.ui import icons, theme

    app = QtWidgets.QApplication.instance() or QtWidgets.QApplication([])
    theme.install(app)
    families = theme.load_fonts()
    theme.identify(app)

    checks = [
        ("wordmark face", families["display"] != families["sans"],
         families["display"]),
        ("body faces", families["mono"] != "monospace", families["mono"]),
        ("stylesheet", len(theme.stylesheet()) > 1000,
         f"{len(theme.stylesheet())} chars"),
        ("icons", len(icons.available()) >= 6,
         ", ".join(icons.available())),
        ("application mark", not app.windowIcon().isNull(),
         f"{len(app.windowIcon().availableSizes())} sizes"),
    ]
    failed = 0
    for name, ok, detail in checks:
        print(f"  {'ok  ' if ok else 'FAIL'}  {name}: {detail}")
        failed += not ok

    print(f"  ok    darlaston {__version__}, Qt {QtCore.qVersion()}, "
          f"OpenCV {cv2.__version__}, numpy {numpy.__version__}")
    return 1 if failed else 0


if __name__ == "__main__":
    # Required before anything else on Windows and macOS: without it a
    # frozen app that starts a process re-executes the whole bundle
    # instead of the child, which shows up as the window opening twice
    # and then forking for ever.
    multiprocessing.freeze_support()

    if "--selftest" in sys.argv[1:]:
        raise SystemExit(selftest())

    from darlaston.ui.main import main
    sys.exit(main())
